import { LinearGradient } from '../constants';
import { JanuaryColor, JANUARY_COLORS } from '../color'

export const BEGINNING_OF_JANUARY = new Date(2024, 0);

export interface Time {
  name: string;
  backgroundColor: JanuaryColor;
  background?: LinearGradient; // ick, used for gradients
  foregroundColor: JanuaryColor;
  whiteoutForegroundColors: JanuaryColor[];
  whiteoutSnowflakeColors: JanuaryColor[];
  mountainBackgroundColor: JanuaryColor;
  mountainForegroundColor: JanuaryColor;
}

export const TIMES: Time[] = [
  {
    name: 'weeHours',
    background: {
      degrees: 60,
      color1: JANUARY_COLORS.indigo,
      color2: JANUARY_COLORS.black,
    },
    backgroundColor: JANUARY_COLORS.indigo,
    foregroundColor: JANUARY_COLORS.white,
    whiteoutForegroundColors: [JANUARY_COLORS.indigo, JANUARY_COLORS.violet, JANUARY_COLORS.dullViolet, JANUARY_COLORS.black],
    whiteoutSnowflakeColors: [JANUARY_COLORS.white, JANUARY_COLORS.paleViolet],
    mountainBackgroundColor: JANUARY_COLORS.black,
    mountainForegroundColor: JANUARY_COLORS.white,
  },
  {
    name: 'dawn',
    backgroundColor: JANUARY_COLORS.dullViolet,
    foregroundColor: JANUARY_COLORS.black,
    whiteoutForegroundColors: [JANUARY_COLORS.black, JANUARY_COLORS.violet, JANUARY_COLORS.dullViolet],
    whiteoutSnowflakeColors: [JANUARY_COLORS.white, JANUARY_COLORS.paleViolet],
    mountainBackgroundColor: JANUARY_COLORS.gray,
    mountainForegroundColor: JANUARY_COLORS.white,
  },
  {
    name: 'sunrise',
    backgroundColor: JANUARY_COLORS.violet,
    background: {
      degrees: 60,
      color1: JANUARY_COLORS.gold,
      color2: JANUARY_COLORS.violet,
    },
    foregroundColor: JANUARY_COLORS.red,
    whiteoutForegroundColors: [JANUARY_COLORS.red, JANUARY_COLORS.violet, JANUARY_COLORS.gold],
    whiteoutSnowflakeColors: [JANUARY_COLORS.yellow, JANUARY_COLORS.paleViolet],
    mountainBackgroundColor: JANUARY_COLORS.gray,
    mountainForegroundColor: JANUARY_COLORS.white,
  },
  {
    name: 'morning',
    backgroundColor: JANUARY_COLORS.blue,
    foregroundColor: JANUARY_COLORS.white,
    whiteoutForegroundColors: [JANUARY_COLORS.black, JANUARY_COLORS.blue],
    whiteoutSnowflakeColors: [JANUARY_COLORS.white],
    mountainBackgroundColor: JANUARY_COLORS.white,
    mountainForegroundColor: JANUARY_COLORS.black,
  },
  {
    name: 'midday',
    backgroundColor: JANUARY_COLORS.cyan,
    foregroundColor: JANUARY_COLORS.yellow,
    whiteoutForegroundColors: [JANUARY_COLORS.black, JANUARY_COLORS.gold, JANUARY_COLORS.cyan],
    whiteoutSnowflakeColors: [JANUARY_COLORS.white, JANUARY_COLORS.yellow],
    mountainBackgroundColor: JANUARY_COLORS.white,
    mountainForegroundColor: JANUARY_COLORS.black,
  },
  {
    name: 'afternoon',
    backgroundColor: JANUARY_COLORS.blue,
    foregroundColor: JANUARY_COLORS.white,
    whiteoutForegroundColors: [JANUARY_COLORS.black, JANUARY_COLORS.blue],
    whiteoutSnowflakeColors: [JANUARY_COLORS.white],
    mountainBackgroundColor: JANUARY_COLORS.white,
    mountainForegroundColor: JANUARY_COLORS.black,
  },
  {
    name: 'sunset',
    backgroundColor: JANUARY_COLORS.violet,
    background: {
      degrees: 150,
      color1: JANUARY_COLORS.violet,
      color2: JANUARY_COLORS.gold,
    },
    foregroundColor: JANUARY_COLORS.red,
    whiteoutForegroundColors: [JANUARY_COLORS.red, JANUARY_COLORS.violet, JANUARY_COLORS.gold],
    whiteoutSnowflakeColors: [JANUARY_COLORS.yellow, JANUARY_COLORS.paleViolet],
    mountainBackgroundColor: JANUARY_COLORS.gray,
    mountainForegroundColor: JANUARY_COLORS.white,
  },
  {
    name: 'dusk',
    backgroundColor: JANUARY_COLORS.dullViolet,
    foregroundColor: JANUARY_COLORS.black,
    whiteoutForegroundColors: [JANUARY_COLORS.black, JANUARY_COLORS.violet, JANUARY_COLORS.dullViolet],
    whiteoutSnowflakeColors: [JANUARY_COLORS.white, JANUARY_COLORS.paleViolet],
    mountainBackgroundColor: JANUARY_COLORS.gray,
    mountainForegroundColor: JANUARY_COLORS.white,
  },
  {
    name: 'night',
    backgroundColor: JANUARY_COLORS.indigo,
    foregroundColor: JANUARY_COLORS.white,
    background: {
      degrees: 150,
      color1: JANUARY_COLORS.black,
      color2: JANUARY_COLORS.indigo,
    },
    whiteoutForegroundColors: [JANUARY_COLORS.indigo, JANUARY_COLORS.violet, JANUARY_COLORS.dullViolet],
    whiteoutSnowflakeColors: [JANUARY_COLORS.white, JANUARY_COLORS.paleViolet],
    mountainBackgroundColor: JANUARY_COLORS.black,
    mountainForegroundColor: JANUARY_COLORS.white,
  },
] as const;

export type Weather = 'night' | 'poemstorm' | 'whiteout' | 'snowsight' | 'cloudy' | 'clear'; // to add? whiteout / midday / all by dispensation

export interface TimeForDay {
  hours: number;
  minutes: number;
  weather: Weather;
  temperature?: number;
  prediction?: string;
}
export interface Day {
  weeHours: TimeForDay;
  dawn: TimeForDay;
  sunrise: TimeForDay;
  morning: TimeForDay;
  midday: TimeForDay;
  afternoon: TimeForDay;
  sunset: TimeForDay;
  dusk: TimeForDay;
  night: TimeForDay;
}

export type TimeName = 'weeHours' | 'dawn' | 'sunrise' | 'morning' | 'midday' | 'afternoon' | 'sunset' | 'dusk' | 'night';

export const JANUARY_SCHEDULE: Day[] = [
  {
    weeHours: { // night wind
      hours: 0,
      minutes: 0,
      weather: 'poemstorm',
      temperature: 4,
      prediction: 'Severe brainstorm. Temperatures in the single digits, stanzas coming through so clearly they are legible even at night.',
    },
    dawn: {
      hours: 6,
      minutes: 20,
      weather: 'whiteout',
      temperature: 2,
      prediction: 'Storm worsening, words losing all coherence. No visibility. Avoid travel.'

    },
    sunrise: { // JANUARY
      hours: 8,
      minutes: 13,
      weather: 'poemstorm',
      temperature: 3,
      prediction: 'Ring in the new year with blustering snow and a danger of freezing acrostics.',
    },
    morning: { // Weathering the Word
      hours: 8,
      minutes: 21,
      weather: 'poemstorm',
      temperature: 8,
      prediction: 'Storm continues; expect increase of 5-10 degrees, bringing hopes that skillful use of language can quell chaos',
    },
    midday: { // Midday
      hours: 12,
      minutes: 13,
      weather: 'poemstorm',
      temperature: 9,
      prediction: 'Sun visible through flying words; storm dying down at last.',
    },
    afternoon: { // Snowsight V
      hours: 12,
      minutes: 44,
      weather: 'snowsight',
      temperature: 10,
      prediction: 'A brief afternoon lull; expect sun on snow, light breezes, and the sort of liminal weather that allows commerce with spirits from Beyond.',
    },
    sunset: {
      hours: 16,
      minutes: 37,
      weather: 'whiteout',
      temperature: 11,
      prediction: 'Blizzard back with a vengeance. Stay inside, folks.',
    },
    dusk: {
      hours: 16,
      minutes: 45,
      weather: 'cloudy',
      temperature: 10,
      prediction: 'Dense cloud cover; a time of confusion, encounters with Wanderers, and murky visions of the past',
    },
    night: {
      hours: 18,
      minutes: 37,
      weather: 'cloudy',
      temperature: 12,
      prediction: 'Still cloudy.',
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      temperature: 10,
      prediction: 'Cloud cover growing oppressive. Air quality declining due to inversion.'
    },
    dawn: {
      hours: 6,
      minutes: 21,
      weather: 'cloudy',
      temperature: 14,
      prediction: 'Air quality unhealthy for sensitive groups',
    },
    sunrise: {
      hours: 8,
      minutes: 12,
      weather: 'whiteout',
      temperature: 12,
      prediction: 'Rising winds stirring up blizzard, maybe it\'ll clear out some of this smog.'
    },
    morning: {
      hours: 8,
      minutes: 19,
      weather: 'whiteout',
      prediction: 'Still blizzard conditions. Stay safe.',
      temperature: 14,
    },
    midday: { // snowsight dissolving into sunlight
      hours: 12,
      minutes: 14,
      weather: 'snowsight',
      prediction: 'Sunny; a calm stretch beginning, perfect for skiing or considering the meaning of sunlight.',
      temperature: 15,
    },
    afternoon: { // Faceless
      hours: 12,
      minutes: 45,
      weather: 'clear',
      prediction: 'Clear, warming up into the low twenties. A good day to explore.',
      temperature: 21,
    },
    sunset: { // Faceless
      hours: 16,
      minutes: 38,
      weather: 'clear',
      prediction: 'Weather continuing clear, temps dipping back into the single digits soon.',
      temperature: 15,
    },
    dusk: { // Faceless
      hours: 16,
      minutes: 46,
      weather: 'clear',
      prediction: 'Still clear; expect to be addressed by the narrator.',
      temperature: 10,
    },
    night: {
      hours: 18,
      minutes: 38,
      weather: 'night',
      temperature: 6,
      prediction: 'A comparatively peaceful, if frigid, night.'
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'night',
      prediction: 'Still calm',
      temperature: 3,
    },
    dawn: { // Mirrors
      hours: 6,
      minutes: 21,
      weather: 'clear',
      prediction: 'Questions of identity becoming prominent in the early morning; some danger of subzero temperatures; abstraction levels getting dangerously high',
      temperature: 2,
    },
    sunrise: { // mirrors
      hours: 8,
      minutes: 12,
      weather: 'clear',
      prediction: 'Moving into the world outside the mind.',
      temperature: 4,
    },
    morning: { // mirrors
      hours: 8,
      minutes: 19,
      weather: 'clear',
      prediction: 'Weather continuing clear and warming, but narrator and snow both perilously reflective. Wear sunglasses.',
      temperature: 10,
    },
    midday: { // mirrors
      hours: 12,
      minutes: 14,
      weather: 'clear',
      prediction: 'Lovely stretch of weather we\'re having here, even if the reality all that light reveals is still mystifying. Makes a person think about springtime, but that\'s a long ways off, folks.',
      temperature: 12,
    },
    afternoon: { // mirrors
      hours: 12,
      minutes: 45,
      weather: 'clear',
      prediction: 'Those of you involved in today\'s noon weather incident will find the afternoon hours a good time to relax: sunny, comparatively warm, and uneventful.',
      temperature: 15,
    },
    sunset: { // All by Dispensation
      hours: 16,
      minutes: 39,
      weather: 'poemstorm',
      prediction: 'This brief resurgence of stormy weather will combine with the sunset to present some lovelier-than-usual vistas. Worth seeing but not for the faint of heart.',
      temperature: 15
    },
    dusk: {
      hours: 16,
      minutes: 47,
      weather: 'snowsight',
      prediction: 'Clearing off again, but not quite exploring weather and getting dark quickly; expect quiet conversations about disappointing otherworlds.',
      temperature: 17,
    },
    night: {
      hours: 18,
      minutes: 39,
      weather: 'cloudy',
      prediction: 'Cloud cover returning, temperature rising into the mid twenties.',
      temperature: 24,
    }, 
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Still cloudy.',
      temperature: 22,
    },
    dawn: {
      hours: 6,
      minutes: 21,
      weather: 'cloudy',
      prediction: 'Cloud cover continuing; we promise the sun\'s still out there somewhere, friends.',
      temperature: 22,
    },
    sunrise: {
      hours: 8,
      minutes: 12,
      weather: 'cloudy',
      prediction: 'Sunrise barely visible through dense cloud cover and fog',
      temperature: 23,
    },
    morning: {
      hours: 8,
      minutes: 19,
      weather: 'snowsight',
      prediction: 'Expect to consider the complexity and multiplicity of identity as the sun emerges briefly from the clouds.',
      temperature: 25,
    },
    midday: {
      hours: 12,
      minutes: 15,
      weather: 'whiteout',
      prediction: 'Blizzard conditions. Travelers beware.',
      temperature: 24,
    },
    afternoon: {
      hours: 12,
      minutes: 46,
      weather: 'poemstorm',
      prediction: 'Storm slowing but not stopping; expect abecedaria and absurdism',
      temperature: 26,
    },
    sunset: {
      hours: 16,
      minutes: 40,
      weather: 'poemstorm',
      prediction: 'What\'s better for a stormy sunset than an ars poetica?',
      temperature: 25,
    },
    dusk: {
      hours: 16,
      minutes: 48,
      weather: 'poemstorm',
      prediction: 'Conditions returning to normal, but with the appearance of some residual words; nothing that will stick.',
      temperature: 24,
    },
    night: {
      hours: 18,
      minutes: 40,
      weather: 'cloudy',
      prediction: 'Back to that endless cloud cover.',
      temperature: 26,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Continuing cloud cover',
      temperature: 27,
    },
    dawn: {
      hours: 6,
      minutes: 21,
      weather: 'cloudy',
      prediction: 'Still these accursed clouds.',
      temperature: 26,
    },
    sunrise: {
      hours: 8,
      minutes: 12,
      weather: 'cloudy',
      prediction: 'Sunrise vs clouds, but the sun is losing this round.',
      temperature: 28,
    },
    morning: {
      hours: 8,
      minutes: 19,
      weather: 'snowsight',
      prediction: 'Clearing up and warming up to near freezing. Great time to consider play as a phenomenon, or else get in a snowball fight with your kids.',
      temperature: 31,
    },
    midday: {
      hours: 12,
      minutes: 15,
      weather: 'clear',
      prediction: 'Once again time to get out there with the snowshoes and explore; it\'s a maze out there but at least you\'ve got the sun and some decent temperatures, for a change.',
      temperature: 29,
    },
    afternoon: {
      hours: 12,
      minutes: 46,
      weather: 'clear',
      prediction: 'Sunny and hovering around freezing; the unwary might get drafted into quests.',
      temperature: 30,
    },
    sunset: {
      hours: 16,
      minutes: 41,
      weather: 'clear',
      prediction: 'Questing continues past sunset.',
      temperature: 27,
    },
    dusk: {
      hours: 16,
      minutes: 49,
      weather: 'clear',
      prediction: 'In which we learn quests are not for the faint of heart, as if we didn\'t already know. Temperatures dropping precipitously.',
      temperature: 24,
    },
    night: {
      hours: 18,
      minutes: 41,
      weather: 'clear',
      temperature: 16,
      prediction: 'Sleep is for the week on a beautiful starry night like this. Keep searching.'
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'clear',
      prediction: 'Getting lost is a part of the learning process, friends. Keep on keeping on.',
      temperature: 15,
    },
    dawn: {
      hours: 6,
      minutes: 21,
      weather: 'clear',
      prediction: 'Do not despair; the darkest hour is the hour before the dawn; don\'t you see that light in the east?',
      temperature: 14,
    },
    sunrise: {
      hours: 8,
      minutes: 12,
      weather: 'clear',
      prediction: 'A truly shattering sunrise with a vision to match it for those who\'ve been out all night',
      temperature: 14,
    },
    morning: {
      hours: 8,
      minutes: 19,
      weather: 'clear',
      prediction: 'Temperatures and abstraction levels both rising after that brief glimpse.',
      temperature: 19,
    },
    midday: {
      hours: 12,
      minutes: 15,
      weather: 'cloudy',
      prediction: 'Back into the winter netherworld of endless clouds.',
      temperature: 20,
    },
    afternoon: {
      hours: 12,
      minutes: 46,
      weather: 'cloudy',
      prediction: 'Still cloudy.',
      temperature: 22,
    },
  sunset: {
      hours: 16,
      minutes: 42,
      weather: 'snowsight',
      prediction: 'Clearing off for a bit, expect a magnificent sunset; perfect weather to contemplate the meanings of colors.',
      temperature: 20,
    },
    dusk: {
      hours: 16,
      minutes: 50,
      weather: 'cloudy',
      prediction: 'Still cloudy. Thinking about an early bedtime? Don\'t blame you.',
      temperature: 21,
    },
    night: {
      hours: 18,
      minutes: 42,
      weather: 'cloudy',
      prediction: 'Cloudy and uneventful night.',
      temperature: 20,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Continuing cloudy',
      temperature: 19,
    },
    dawn: {
      hours: 6,
      minutes: 20,
      weather: 'clear',
      prediction: 'Weather clearing up at last, things becoming more solid out there for all of us.',
      temperature: 16,
    },
    sunrise: {
      hours: 8,
      minutes: 12,
      weather: 'clear',
      prediction: 'No more overpowering sunrise visions for a bit but still pretty, reality slowly growing more distinct.',
      temperature: 18,
    },
    morning: {
      hours: 8,
      minutes: 19,
      weather: 'clear',
      prediction: 'Still sunny, expect to get a more general lay of the land.',
      temperature: 19,
    },
    midday: {
      hours: 12,
      minutes: 16,
      weather: 'clear',
      prediction: 'With the zenith of the sun comes the zenith of our hopes: the sight of a mountain in the distance.',
      temperature: 22,
    },
    afternoon: {
      hours: 12,
      minutes: 47,
      weather: 'clear',
      prediction: 'A day of progress. Keep on and you won\'t believe how far you\'ll get!',
      temperature: 20,
    },
    sunset: {
      hours: 16,
      minutes: 43,
      weather: 'clear',
      prediction: 'Continuing clear; a day for momentous decisions.',
      temperature: 18,
    },
    dusk: {
      hours: 16,
      minutes: 51,
      weather: 'snowsight',
      prediction: 'Clear night, high likelihood of discussions about music',
      temperature: 17,
    },
    night: {
      hours: 18,
      minutes: 43,
      weather: 'night',
      prediction: 'Sleep; warm front on its way, don\'t mind the wind.',
      temperature: 21,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'night',
      prediction: 'Calm before the storm.',
      temperature: 23,
    },
    dawn: { // hawthorne of Out
      hours: 6,
      minutes: 20,
      weather: 'poemstorm',
      prediction: 'These brainstorms can sure be isolating, and isolation\'s clearly on whatever mind is out there.',
      temperature: 24,
    },
    sunrise: { // catsout
      hours: 8,
      minutes: 11,
      weather: 'poemstorm',
      prediction: 'Storm continues; whatever the poem suggests, keep your furry friends safe indoors.',
      temperature: 23,
    },
    morning: { // macdonald
      hours: 8,
      minutes: 18,
      weather: 'poemstorm',
      prediction: 'Still all about going in and out; still should stay inside!',
      temperature: 26,
    },
    midday: { // circles
      hours: 12,
      minutes: 16,
      weather: 'poemstorm',
      prediction: 'Storm continues.',
      temperature: 27,
    },
    afternoon: { // outfinale
      hours: 12,
      minutes: 47,
      weather: 'poemstorm',
      prediction: 'We\'ve almost seen the worst of this storm, and it was a doozy. Best to hold off on travel till tomorrow, though.',
      temperature: 29,
    },
    sunset: {
      hours: 16,
      minutes: 44,
      weather: 'whiteout',
      prediction: 'Flying words and flying snow.',
      temperature: 26,
    },
    dusk: {
      hours: 16,
      minutes: 52,
      weather: 'snowsight',
      prediction: 'Clearing up but Jennie\'s sleepy and reminiscing about boring children\'s books for some reason.',
      temperature: 25,
    },
    night: {
      hours: 18,
      minutes: 44,
      weather: 'cloudy',
      prediction: 'Back into the clouds.',
      temperature: 24,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Still cloudy.',
      temperature: 24,
    },
    dawn: {
      hours: 6,
      minutes: 20,
      weather: 'cloudy',
      prediction: 'Cloudy as ever.',
      temperature: 23,
    },
    sunrise: { // all by dispensation
      hours: 8,
      minutes: 11,
      weather: 'poemstorm',
      prediction: 'Lovely sunrise but snow sure flying.',
      temperature: 23,
    },
    morning: { // old gold
      hours: 8,
      minutes: 18,
      weather: 'clear',
      prediction: 'Clearing up, a good time to reflect on the past and use it to inspire the future.',
      temperature: 24,
    },
    midday: { // midday
      hours: 12,
      minutes: 17,
      weather: 'poemstorm',
      prediction: 'More words.',
      temperature: 25,
    },
    afternoon: {
      hours: 12,
      minutes: 48,
      weather: 'snowsight',
      prediction: 'Jennie\'s back, on about identity again',
      temperature: 26,
    },
    sunset: {
      hours: 16,
      minutes: 46,
      weather: 'cloudy',
      prediction: 'Damn clouds again.',
      temperature: 25,
    },
    dusk: {
      hours: 16,
      minutes: 54,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 24,
    },
    night: {
      hours: 18,
      minutes: 45,
      weather: 'cloudy',
      prediction: 'Still cloudy.',
      temperature: 24,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloud cover continues',
      temperature: 25,
    },
    dawn: {
      hours: 6,
      minutes: 20,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 25,
    },
    sunrise: {
      hours: 8,
      minutes: 11,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 25,
    },
    morning: {
      hours: 8,
      minutes: 18,
      weather: 'snowsight',
      prediction: 'Close encounter of the Jennie kind; premature concern about the heat of the summer even though the temperature is hovering around 25 degrees',
      temperature: 25,
    },
    midday: { // trying
      hours: 12,
      minutes: 17,
      weather: 'clear',
      prediction: 'The air is clearing, and human endeavor begins to feel possible again.',
      temperature: 24,
    },
    afternoon: { // emma draft
      hours: 12,
      minutes: 48,
      weather: 'clear',
      prediction: 'Progress toward goals, continuing clear.',
      temperature: 26,
    },
    sunset: { // emma draft still
      hours: 16,
      minutes: 47,
      weather: 'clear',
      prediction: 'Keep a work on, friends, while the weather is clear',
      temperature: 24,
    },
    dusk: { // alien in the yard? what is this? down + mountain?
      hours: 16,
      minutes: 55,
      weather: 'clear',
      prediction: 'With the sun down and no clouds in the way, there might be some surprises outside.',
      temperature: 22,
    },
    night: {
      hours: 18,
      minutes: 46,
      weather: 'night',
      prediction: 'Goodnight, sleep tight.',
      temperature: 20,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'night',
      prediction: 'zzzzzzzzz',
      temperature: 19,
    },
    dawn: { // emma draft
      hours: 6,
      minutes: 20,
      weather: 'clear',
      prediction: 'Still clear, a good time to get up early and work toward your goals.',
      temperature: 20,
    },
    sunrise: { // emma draft
      hours: 8,
      minutes: 10,
      weather: 'clear',
      prediction: 'Still good working weather.',
      temperature: 21,
    },
    morning: { // emma draft
      hours: 8,
      minutes: 17,
      weather: 'clear',
      prediction: 'Clear morning, approaching completion.',
      temperature: 23,
    },
    midday: { // first promontory
      hours: 12,
      minutes: 18,
      weather: 'clear',
      prediction: 'Savor that sense of accomplishment while it lasts.',
      temperature: 25,
    },
    afternoon: { // fail to edit
      hours: 12,
      minutes: 49,
      weather: 'clear',
      prediction: 'Still clear; a time for rest, relaxation, and a warm sense of accomplishment.',
      temperature: 26,
    },
    sunset: { // tell me you down
      hours: 16,
      minutes: 48,
      weather: 'clear',
      prediction: 'Clear, magnificent sunset, a time to look far ahead.',
      temperature: 24,
    },
    dusk: { // fail to edit
      hours: 16,
      minutes: 56,
      weather: 'clear',
      prediction: 'Clear and uneventful.',
      temperature: 22,
    },
    night: { // alien dreams
      hours: 18,
      minutes: 47,
      weather: 'clear',
      prediction: 'Aliens invading our dreams.',
      temperature: 20,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'night',
      prediction: 'Sleep soundly.',
      temperature: 19,
    },
    dawn: { // whole selves to work
      hours: 6,
      minutes: 19,
      weather: 'snowsight',
      prediction: 'Fitful partial sun, wistful thoughts about rain, oddly enough, though snow seems more likely.',
      temperature: 20,
    },
    sunrise: { // merry wanderers
      hours: 8,
      minutes: 10,
      weather: 'poemstorm',
      prediction: 'Meditations on rain seem to have kicked up another brainstorm.',
      temperature: 20,
    },
    morning: {
      hours: 8,
      minutes: 17,
      weather: 'whiteout',
      prediction: 'Blizzard conditions. Avoid unnecessary travel.',
      temperature: 21, 
    },
    midday: { // midday
      hours: 12,
      minutes: 18,
      weather: 'poemstorm',
      prediction: 'Snow still flying, sun starting to peek through.',
      temperature: 23,
    },
    afternoon: { // truth and imagination
      hours: 12,
      minutes: 49,
      weather: 'clear',
      prediction: 'Sunny and calm, inviting efforts to understand truth and the imagination',
      temperature: 25,
    },
    sunset: { // paper on D
      hours: 16,
      minutes: 49,
      weather: 'clear',
      prediction: 'Still clear, ambitious overly vague ideas devolving into perorations on favorite authors.',
      temperature: 22,
    },
    dusk: { // math
      hours: 16,
      minutes: 57,
      weather: 'clear',
      prediction: 'Still clear, cross-disciplinary inquiries liable to commence.',
      temperature: 21,
    },
    night: {
      hours: 18,
      minutes: 48,
      weather: 'night',
      prediction: 'Bedtime!',
      temperature: 20,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'night',
      prediction: 'Clear and uneventful night.',
      temperature: 20,
    },
    dawn: { // allegory
      hours: 6,
      minutes: 19,
      weather: 'clear',
      prediction: 'Fine weather continuing; in which our reach may continue to exceed our grasp.',
      temperature: 19,
    },
    sunrise: { // allegory still
      hours: 8,
      minutes: 9,
      weather: 'clear',
      prediction: 'Fine thoughts in the clear sunrise.',
      temperature: 20,
    },
    morning: {
      hours: 8,
      minutes: 16,
      weather: 'snowsight',
      prediction: 'Partial sun; the significance of nerds on the mind.',
      temperature: 22,
    },
    midday: { // outsider art
      hours: 12,
      minutes: 18,
      weather: 'clear',
      prediction: 'Miraculously clear; academic inquiries may spill into new artistic ambitions.',
      temperature: 22,
    },
    afternoon: { // outsider art
      hours: 12,
      minutes: 49,
      weather: 'clear',
      prediction: 'Clear and inspiring weather continues.',
      temperature: 23,
    },
    sunset: { // august
      hours: 16,
      minutes: 51,
      weather: 'clear',
      prediction: 'In spite of the frigidity of both the author\'s soul and the weather, clear weather inspires us to attempt writing about August.',
      temperature: 21,
    },
    dusk: { // august
      hours: 16,
      minutes: 59,
      weather: 'clear',
      prediction: 'Writing continues in the clear dusk. Temperatures dropping.',
      temperature: 18,
    },
    night: {
      hours: 18,
      minutes: 49,
      weather: 'night',
      prediction: 'A frosty, clear, and uneventful night.',
      temperature: 16,
    },
  },
  {
    weeHours: { // love
      hours: 0,
      minutes: 0,
      weather: 'poemstorm',
      prediction: 'Another brainstorm; we knew this still weather was too good to last. Don\'t let the howling wind keep you up, or do. Love on the brain.',
      temperature: 13,
    },
    dawn: { // love
      hours: 6,
      minutes: 19,
      weather: 'poemstorm',
      prediction: 'Storm intensifies',
      temperature: 15,
    },
    sunrise: { // love
      hours: 8,
      minutes: 9,
      weather: 'poemstorm',
      prediction: 'A sunrise of majestic and even exuberant beauty if you care for subzero windchills.',
      temperature: 15,
    },
    morning: { // love
      hours: 8,
      minutes: 16,
      weather: 'poemstorm',
      prediction: 'Storm fading at last. Temperatures likely to climb.',
      temperature: 17,
    },
    midday: {
      hours: 12,
      minutes: 19,
      weather: 'snowsight',
      prediction: 'Jennie back in the sun to discuss the apocalyptic condition of the world.',
      temperature: 20,
    },
    afternoon: {
      hours: 12,
      minutes: 50,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 22,
    },
    sunset: {
      hours: 16,
      minutes: 52,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 22,
    },
    dusk: {
      hours: 17,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 23,
    },
    night: {
      hours: 18,
      minutes: 50,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 23,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'night',
      prediction: 'Weather clearing off, temps dropping again.',
      temperature: 18,
    },
    dawn: { // job search
      hours: 6,
      minutes: 18,
      weather: 'clear',
      prediction: 'More material ambitions begin on this clear but cold morning.',
      temperature: 19,
    },
    sunrise: { // application accepted
      hours: 8,
      minutes: 8,
      weather: 'clear',
      prediction: 'Sun splendid, temperature unlikely torise above 22 today.',
      temperature: 20,
    },
    morning: { // digging
      hours: 8,
      minutes: 15,
      weather: 'clear',
      prediction: 'Continuing clear and cold.',
      temperature: 20,
    },
    midday: { // art and light (?)
      hours: 12,
      minutes: 19,
      weather: 'clear',
      prediction: 'Art and employment at the same time! Sunny weather makes anything possible.',
      temperature: 20,
    },
    afternoon: {
      hours: 12,
      minutes: 50,
      weather: 'snowsight',
      prediction: 'Jennie arrives to converse about Blake; partial sun.',
      temperature: 21,
    },
    sunset: { // poetry translation
      hours: 16,
      minutes: 53,
      weather: 'clear',
      prediction: 'Cold weather inspires efforts at poetry translation.',
      temperature: 19,
    },
    dusk: {
      hours: 17,
      minutes: 1,
      weather: 'cloudy',
      prediction: 'Cloud cover keeping temps up.',
      temperature: 20,
    },
    night: {
      hours: 18,
      minutes: 51,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 20,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 21,
    },
    dawn: { // sonia in hell
      hours: 6,
      minutes: 18,
      weather: 'clear',
      prediction: 'Clearing off for Cathar-inspired meditations on animal rights and hell.',
      temperature: 18,
    },
    sunrise: { // all by dispensation
      hours: 8,
      minutes: 7,
      weather: 'poemstorm',
      prediction: 'Flying words, inspiring for the sunrise.',
      temperature: 17,
    },
    morning: {
      hours: 8,
      minutes: 14,
      weather: 'snowsight',
      prediction: 'Authenticity in the workplace comes under discussion as the winds slow down.',
      temperature: 18,
    },
    midday: { // prayer and Coleridge
      hours: 12,
      minutes: 19,
      weather: 'clear',
      prediction: 'Sunny and calm once again; will it last? Will this lull give us the ability to accomplish more of our dreams?',
      temperature: 22,
    },
    afternoon: { // tree of life
      hours: 12,
      minutes: 50,
      weather: 'clear',
      prediction: 'Sunny and productive weather.',
      temperature: 23,
    },
    sunset: {// tree of life
      hours: 16,
      minutes: 55,
      weather: 'clear',
      prediction: 'Clear at sunset tonight.',
      temperature: 21,
    },
    dusk: { // enumerate tree of life
      hours: 17,
      minutes: 3,
      weather: 'clear',
      prediction: 'Making art is one thing, but understanding it? Efforts continue.',
      temperature: 19,
    },
    night: { // enumerate tree of life
      hours: 18,
      minutes: 52,
      weather: 'clear',
      prediction: 'Clear weather inspires all-night efforts if you have the energy.',
      temperature: 18,
    },
  },
  {
    weeHours: { // enumerate tree of life
      hours: 0,
      minutes: 0,
      weather: 'clear',
      prediction: 'Progress will continue if you have the energy... No storm yet to impede.',
      temperature: 16,
    },
    dawn: { // exhaustion
      hours: 6,
      minutes: 17,
      weather: 'clear',
      prediction: 'In a startling turn of events, all-nighters lead to exhaustion despite clear skies.',
      temperature: 18,
    },
    sunrise: {
      hours: 8,
      minutes: 7,
      weather: 'whiteout',
      prediction: 'Brainstorm returns with a vengeance. Stay in.',
      temperature: 17,
    },
    morning: {
      hours: 8,
      minutes: 14,
      weather: 'snowsight',
      prediction: 'On this glorious partially sunny winter morning, Jennie reflects on...glory.',
      temperature: 16,
    },
    midday: { // truth, now paradoxes
      hours: 12,
      minutes: 20,
      weather: 'poemstorm',
      prediction: 'When your high-flown notions about truth shrink into several aphorisms using the same words with different meanings, you know you\'ve been at it too long. Stay in; brainstorm continues.',
      temperature: 18,
    },
    afternoon: {
      hours: 12,
      minutes: 51,
      weather: 'whiteout',
      prediction: 'Blizzard.',
      temperature: 17,
    },
    sunset: {
      hours: 16,
      minutes: 56,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 20,
    },
    dusk: {
      hours: 17,
      minutes: 4,
      weather: 'cloudy',
    },
    night: {
      hours: 18,
      minutes: 53,
      weather: 'cloudy',
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 21,
    },
    dawn: { // firebird painting
      hours: 6,
      minutes: 17,
      weather: 'clear',
      prediction: 'Clearing off again; brief stint of activity possible.',
      temperature: 18,
    },
    sunrise: { // firebird painting
      hours: 8,
      minutes: 6,
      weather: 'clear',
      prediction: 'Clear sunrise.',
      temperature: 20,
    },
    morning: { // firebird painting interpretation
      hours: 8,
      minutes: 13,
      weather: 'clear',
      prediction: 'Trying to understand art once again gets us only so far however clear the sky may be.',
      temperature: 20,
    },
    midday: { // midday
      hours: 12,
      minutes: 20,
      weather: 'poemstorm',
      prediction: 'Storm threatening.',
      temperature: 19,
    },
    afternoon: {
      hours: 12,
      minutes: 51,
      weather: 'snowsight',
      prediction: 'Light and bright still, but Jennie\'s feeling morbid: damnation on the mind.',
      temperature: 18,
    },
    sunset: { // again
      hours: 16,
      minutes: 58,
      weather: 'poemstorm',
      prediction: 'Storm heating up, er, cooling down again for sunset.',
      temperature: 17,
    },
    dusk: { // firebird abstract
      hours: 17,
      minutes: 6,
      weather: 'clear',
      prediction: 'Another lull.',
      temperature: 16,
    },
    night: { // firebird abstract
      hours: 18,
      minutes: 55,
      weather: 'clear',
      prediction: 'Clear and getting down there, folks. Let\'s hope we stay out of the single digits.',
      temperature: 14,
    },
  },
  {
    weeHours: { // firebird abstract interpretation
      hours: 0,
      minutes: 0,
      weather: 'clear',
      prediction: 'The kind of clarity only icy winter nights can bring.',
      temperature: 10,
    },
    dawn: {
      hours: 6,
      minutes: 16,
      weather: 'cloudy',
      prediction: 'Clouds rolling in.',
      temperature: 11,
    },
    sunrise: {
      hours: 8,
      minutes: 4,
      weather: 'snowsight',
      prediction: 'Red skies in the morning, sailors take warning: Jennie discusses rage.',
      temperature: 8,
    },
    morning: { // hypothermia
      hours: 8,
      minutes: 11,
      weather: 'poemstorm',
      prediction: 'Dipping down close to zero today, maybe even below counting windchill.',
      temperature: 6,
    },
    midday: {
      hours: 12,
      minutes: 21,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 7,      
    },
    afternoon: {
      hours: 12,
      minutes: 52,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 10,
    },
    sunset: {
      hours: 17,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 11,
    },
    dusk: {
      hours: 17,
      minutes: 8,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 12,
    },
    night: {
      hours: 18,
      minutes: 57,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 12,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 11,
    },
    dawn: { // dissolution
      hours: 6,
      minutes: 16,
      weather: 'clear',
      prediction: 'Skies clearing, temperature dropping again.',
      temperature: 6,
    },
    sunrise: { // dissolution
      hours: 8,
      minutes: 5,
      weather: 'clear',
      prediction: 'Danger of frostbite if you venture outside today.',
      temperature: 4,
    },
    morning: { // symbols
      hours: 8,
      minutes: 12,
      weather: 'clear',
      prediction: 'Brrrrrrr.',
      temperature: 3,
    },
    midday: { // symbols
      hours: 12,
      minutes: 20,
      weather: 'clear',
      prediction: 'Sunny but frigid as this arctic vortex deepens.',
      temperature: 2,
    },
    afternoon: {
      hours: 12,
      minutes: 51,
      weather: 'snowsight',
      prediction: 'As this unacceptably cold afternoon wears on, Jennie meditates on the nature of unacceptable and unbearable as concepts.',
      temperature: 3,
    },
    sunset: { // auras
      hours: 16,
      minutes: 59,
      weather: 'clear',
      prediction: 'We may lose some perennials this winter if these temperatures go the way they\'re looking.',
      temperature: 1,
    },
    dusk: { // auras
      hours: 17,
      minutes: 7,
      weather: 'clear',
      prediction: 'Isn\'t the light of the moon coming through your steaming breath sort of like...an aura?',
      temperature: -2,
    },
    night: {
      hours: 18,
      minutes: 56,
      weather: 'night',
      prediction: 'Bundle up.',
      temperature: -5,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Clouds moving in, some relief from these temperatures.',
      temperature: 1,
    },
    dawn: {
      hours: 6,
      minutes: 15,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 2,
    },
    sunrise: {
      hours: 8,
      minutes: 3,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 2,
    },
    morning: {
      hours: 8,
      minutes: 10,
      weather: 'snowsight',
      prediction: 'Clouds lift somewhat, but sun is not the key to warmth this time of year. What is a key? Does it work? Find out from Jennie.',
      temperature: 0,
    },
    midday: {
      hours: 12,
      minutes: 21,
      weather: 'whiteout',
      prediction: 'How the snow even forms at these temperatures is beyond me, but it seems to be; beware low visibility and windchills under ten below.',
      temperature: 3,
    },
    afternoon: {
      hours: 12,
      minutes: 52,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 4,
    },
    sunset: { // jennie in the mirror
      hours: 17,
      minutes: 2,
      weather: 'clear',
      prediction: 'Winds die down, temps stay low.',
      temperature: 5,
    },
    dusk: { // jennie in the mirror
      hours: 17,
      minutes: 10,
      weather: 'clear',
      prediction: 'Clear and cold.',
      temperature: 2,
    },
    night: { // chainlink sky
      hours: 18,
      minutes: 58,
      weather: 'clear',
      prediction: 'Time to rappel through the sky.',
      temperature: 0,
    },
  },
  {
    weeHours: { // chainlink sky
      hours: 0,
      minutes: 0,
      weather: 'clear',
      prediction: 'Temperatures rising.',
      temperature: 5,
    },
    dawn: { // chainlink sky
      hours: 6,
      minutes: 14,
      weather: 'clear',
      prediction: 'Continuing to warm.',
      temperature: 10,
    },
    sunrise: { // cosmic egg
      hours: 8,
      minutes: 2,
      weather: 'clear',
      prediction: 'Clear and almost liveable.',
      temperature: 12,
    },
    morning: { // cosmic egg
      hours: 8,
      minutes: 9,
      weather: 'clear',
      prediction: 'Warming into the double digits again.',
      temperature: 15,
    },
    midday: {
      hours: 12,
      minutes: 21,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 20,
    },
    afternoon: {
      hours: 12,
      minutes: 52,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 20,
    },
    sunset: { // all by dispensation
      hours: 17,
      minutes: 3,
      weather: 'poemstorm',
      prediction: 'Rising winds around sunset.',
      temperature: 17,
    },
    dusk: { // snowsight process theology?
      hours: 17,
      minutes: 11,
      weather: 'snowsight',
      prediction: 'Cloud cover clearing, time to ask ourselves whether whether God can really be perfect. This weather argues against.',
      temperature: 20,
    },
    night: {
      hours: 19,
      minutes: 0,
      weather: 'night',
      prediction: 'Clear and quiet night, we may have seen the worst of this cold snap.',
      temperature: 19,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 20,
    },
    dawn: {
      hours: 6,
      minutes: 14,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 21,
    },
    sunrise: {
      hours: 8,
      minutes: 2,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 20,
    },
    morning: {
      hours: 8,
      minutes: 9,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 22,
    },
    midday: {
      hours: 12,
      minutes: 21,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 23,
    },
    afternoon: {// birthday
      hours: 12,
      minutes: 52,
      weather: 'clear',
      prediction: 'Clearing at last for a very underwhelming celebration.',
      temperature: 24,
    },
    sunset: { // candy
      hours: 17,
      minutes: 5,
      weather: 'clear',
      prediction: 'Weather still clear.',
      temperature: 20,
    },
    dusk: { // bad day
      hours: 17,
      minutes: 13,
      weather: 'snowsight',
      prediction: 'Partly cloudy, can talk to Jennie but she had a bad day.',
      temperature: 19,
    },
    night: {
      hours: 19,
      minutes: 1,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 19,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 19,
    },
    dawn: {
      hours: 6,
      minutes: 13,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 18,
    },
    sunrise: {
      hours: 8,
      minutes: 1,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 20,
    },
    morning: { // gel pens
      hours: 8,
      minutes: 8,
      weather: 'poemstorm',
      prediction: 'Uh-oh, brainstorm starting, steep drop in temperature predicted.',
      temperature: 16,
    },
    midday: {
      hours: 12,
      minutes: 22,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 15,
    },
    afternoon: {
      hours: 12,
      minutes: 53,
      weather: 'whiteout',
      prediction: 'Blizzard whipping up.',
      temperature: 15,
    },
    sunset: { // channeling angels
      hours: 17,
      minutes: 6,
      weather: 'snowsight',
      prediction: 'Sun partly visible during this spectacular sunset, thoughts on automatic writing.',
      temperature: 13,
    },
    dusk: { // likenesses
      hours: 17,
      minutes: 14,
      weather: 'clear',
      prediction: 'You thought you\'d had all the winter you could take? Think again.',
      temperature: 9,
    },
    night: { // death of the rose knight
      hours: 19,
      minutes: 2,
      weather: 'clear',
      prediction: 'Clear, temperatures dipping below zero',
      temperature: -1,
    },
  },
  {
    weeHours: { // death of the rose knight
      hours: 0,
      minutes: 0,
      weather: 'clear',
      prediction: 'Really f***ing cold.',
      temperature: -8,
    },
    dawn: { // mere reality waking
      hours: 6,
      minutes: 12,
      weather: 'clear',
      prediction: 'Cold as death.',
      temperature: -10,
    },
    sunrise: { // mere reality art
      hours: 7,
      minutes: 59,
      weather: 'clear',
      prediction: 'Cold as death.',
      temperature: -9,
    },
    morning: { // sunflowers
      hours: 8,
      minutes: 7,
      weather: 'snowsight',
      prediction: 'Jennie emerges to discuss sunflowers of all things. How is she handling this weather anyway?',
      temperature: -5,
    },
    midday: { // midday
      hours: 12,
      minutes: 22,
      weather: 'poemstorm',
      prediction: 'Respite begins; brief brainstorm bringing in warmer weather.',
      temperature: 10,
    },
    afternoon: { // fall
      hours: 12,
      minutes: 53,
      weather: 'clear',
      prediction: 'No longer quite cold as death, sunny.',
      temperature: 16,
    },
    sunset: { // fall vision
      hours: 17,
      minutes: 7,
      weather: 'clear',
      prediction: 'Cold in the mind, heat in the heart, temperatures evening out on both sides.',
      temperature: 20,
    },
    dusk: { // fall
      hours: 17,
      minutes: 15,
      weather: 'clear',
      prediction: 'Clear still.',
      temperature: 17,
    },
    night: { // man in the moon
      hours: 19,
      minutes: 3,
      weather: 'clear',
      prediction: 'Keep an eye out for personified celestial bodies.',
      temperature: 16,
    },
  },
  {
    weeHours: { // alien abduction
      hours: 0,
      minutes: 0,
      weather: 'clear',
      prediction: 'An exuberantly strange kind of night. Beware aliens.',
      temperature: 20,
    },
    dawn: { // mountain abstract
      hours: 6,
      minutes: 11,
      weather: 'clear',
      prediction: 'Temperatures warming again.',
      temperature: 22,
    },
    sunrise: { // mountain abstract
      hours: 7,
      minutes: 57,
      weather: 'clear',
      prediction: 'Clear sunrise.',
      temperature: 24,
    },
    morning: { // rain painitng
      hours: 8,
      minutes: 5,
      weather: 'clear',
      prediction: 'Clear and productive weather.',
      temperature: 25,
    },
    midday: { // elsewhere beyond elsewhere
      hours: 12,
      minutes: 22,
      weather: 'clear',
      prediction: 'Joyful with relief.',
      temperature: 26,
    },
    afternoon: {
      hours: 12,
      minutes: 53,
      weather: 'whiteout',
      prediction: 'Warm front comes with high winds, probably unsurprisingly.',
      temperature: 27,
    },
    sunset: { // alive
      hours: 17,
      minutes: 8,
      weather: 'poemstorm',
      prediction: 'Windy warm front, temperatures approaching freezing.',
      temperature: 29,
    },
    dusk: {
      hours: 17,
      minutes: 16,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 27,
    },
    night: {
      hours: 19,
      minutes: 5,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 28,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 27,
    },
    dawn: {
      hours: 6,
      minutes: 10,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 26,
    },
    sunrise: {
      hours: 7,
      minutes: 57,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 28,
    },
    morning: { // what should I do?
      hours: 8,
      minutes: 4,
      weather: 'snowsight',
      prediction: 'Glimpses of sun, glimpses of indecisive Jennie.',
      temperature: 30,
    },
    midday: { // portents
      hours: 12,
      minutes: 22,
      weather: 'poemstorm',
      prediction: 'Almost above freezing!',
      temperature: 31,
    },
    afternoon: { // rising temperature/ chinook/Jacob's ladder
      hours: 12,
      minutes: 53,
      weather: 'poemstorm',
      prediction: 'Warm, if windy and stormy, afternoon! Expect slush!',
      temperature: 35,
    },
    sunset: {
      hours: 17,
      minutes: 10,
      weather: 'cloudy',
      prediction: 'Unfortunately all that melted snow is just going to freeze again tonight...',
      temperature: 34,
    },
    dusk: {
      hours: 17,
      minutes: 18,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 31,
    },
    night: {
      hours: 19,
      minutes: 6,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 30,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy, getting a little colder.',
      temperature: 29,
    },
    dawn: {
      hours: 6,
      minutes: 10,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 27,
    },
    sunrise: {
      hours: 7,
      minutes: 56,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 27,
    },
    morning: {
      hours: 8,
      minutes: 3,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 28,
    },
    midday: { // net
      hours: 12,
      minutes: 23,
      weather: 'snowsight',
      prediction: 'Sun makes a brief appearance, as does Jennie, thinking about spring as this warm stretch continues, albeit not as strongly as before..',
      temperature: 26,
    },
    afternoon: {
      hours: 12,
      minutes: 54,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 27,
    },
    sunset: {
      hours: 17,
      minutes: 11,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 26,
    },
    dusk: {
      hours: 17,
      minutes: 19,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 25,
    },
    night: {
      hours: 19,
      minutes: 7,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 23,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 24,
    },
    dawn: {
      hours: 6,
      minutes: 9,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 23,
    },
    sunrise: {
      hours: 7,
      minutes: 55,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 25,
    },
    morning: {
      hours: 8,
      minutes: 2,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 27,
    },
    midday: { // midday
      hours: 12,
      minutes: 23,
      weather: 'poemstorm',
      prediction: 'Squalls of words, lowering the temperature briefly.',
      temperature: 25,
    },
    afternoon: { // July
      hours: 12,
      minutes: 54,
      weather: 'snowsight',
      prediction: 'Sun emerges and winds quiet to let us think about deep summer.',
      temperature: 24,
    },
    sunset: { // winter death
      hours: 17,
      minutes: 13,
      weather: 'poemstorm',
      prediction: 'Stormy weather returns, and colder temps.',
      temperature: 23,
    },
    dusk: { // labyrinth
      hours: 17,
      minutes: 21,
      weather: 'poemstorm',
      prediction: 'You know how sometimes the world seems impossible to navigate? This storm involves those sorts of preoccupations.',
      temperature: 24,
    },
    night: {
      hours: 19,
      minutes: 9,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 22,
    },
  },
  {
    weeHours: {
      hours: 0,
      minutes: 0,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 24,
    },
    dawn: { // knot
      hours: 6,
      minutes: 8,
      weather: 'poemstorm',
      prediction: 'More storm, but once again winds are from the southwest. Looking warmer soon.',
      temperature: 25,
    },
    sunrise: { // desire
      hours: 7,
      minutes: 54,
      weather: 'poemstorm',
      prediction: 'Desire, heated up almost to freezing by these Chinook winds.',
      temperature: 29,
    },
    morning: {
      hours: 8,
      minutes: 1,
      weather: 'poemstorm',
      prediction: 'Storm slowing but not gone.',
      temperature: 31,
    },
    midday: { // fanfiction
      hours: 12,
      minutes: 23,
      weather: 'snowsight',
      prediction: 'Sun\'s emergence brings to mind fanfiction, of all things.',
      temperature: 34,
    },
    afternoon: { // january thaw temps in the mid forties and rain
      hours: 12,
      minutes: 54,
      weather: 'poemstorm',
      prediction: 'Windy and a full forty degrees, with rain! Enjoy it while it lasts, folks.',
      temperature: 40,
    },
    sunset: { // winter sleep
      hours: 17,
      minutes: 15,
      weather: 'poemstorm',
      prediction: 'Cloudy.',
      temperature: 41,
    },
    dusk: {
      hours: 17,
      minutes: 23,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 37,
    },
    night: {
      hours: 19,
      minutes: 10,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 35,
    },
  },
  {
    weeHours: { // night wind
      hours: 0,
      minutes: 0,
      weather: 'poemstorm',
      prediction: 'Winds shifting to the northeast. Temperatures plummetting. Is this weather a rollercoaster or what?',
      temperature: 20,
    },
    dawn: {
      hours: 6,
      minutes: 7,
      weather: 'whiteout',
      prediction: 'Blizzard',
      temperature: 21,
    },
    sunrise: {
      hours: 7,
      minutes: 53,
      weather: 'whiteout',
      prediction: 'Blizzard.',
      temperature: 17,
    },
    morning: { // colorless
      hours: 8,
      minutes: 0,
      weather: 'poemstorm',
      prediction: 'Gotta love this Montana weather, dontcha?',
      temperature: 14,
    },
    midday: {
      hours: 12,
      minutes: 23,
      weather: 'cloudy',
      prediction: 'Temperatures stabilizing as the winds die down and the clouds roll in.',
      temperature: 15,
    },
    afternoon: {
      hours: 12,
      minutes: 54,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 16,
    },
    sunset: {
      hours: 17,
      minutes: 16,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 15,
    },
    dusk: {
      hours: 17,
      minutes: 24,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 13,
    },
    night: {
      hours: 19,
      minutes: 11,
      weather: 'cloudy',
      prediction: 'Cloudy.',
      temperature: 12,
    },
  },
] as const;
